### ISSUE TITLE
Error in android

### ISSUE THREAD

**Issue by abada** [appcelerator-modules/ti.map#163] opened 2016-05-29 13:11 UTC
Just want to create a map 
```
[ERROR] DynamiteModule: Failed to load module descriptor class: Didn't find class 
"com.google.android.gms.dynamite.descriptors.com.google.android.gms.googlecertificates.ModuleDescriptor"
 on path: DexPathList[[zip file "/data/app/com.emoney.salla-2/base.apk"],nativeLibraryDirectories=[/data/app/com.emoney.salla-2/lib/arm, /vendor/lib, /system/lib]]
```

`Ti SDK 5.2.2.GA`
`ti.map 2.3.10`

**Comment by ashcoding** [comment] 2016-05-30 02:00
The error logs seems pretty short.
Could you provide more info on what modules you are using and more crash logs?

**Comment by abada** [comment] 2016-05-30 07:59
That is all log :(

I have  `ti.ga` and  `com.pushwoosh.module` https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/

**Comment by hansemannn** [comment] 2016-05-30 21:53
I don't see how that error is related to ti.map, it's more something n Pushwoosh, since they use GMS to send push notifications.

**Comment by abada** [comment] 2016-05-31 08:33
Hi @hansemannn thank you for   reply

But i disabled all modules except that `ti.map` 

and this error shown

```
ERROR] SensorManager: uid = 10178
[INFO]  SensorManager: registerListenerImpl: listener = android.view.OrientationEventListener$SensorEventListenerImpl@cd20b94, sensor = {Sensor name="BOSCH Acceleration Sensor", vendor="Bosch Sensortec GmbH", version=3060102, type=1, maxRange=156.88, resolution=0.009575196, power=0.13, minDelay=5000}, delay = 200000, handler = null
[INFO]  zzy: Making Creator dynamically
[INFO]  System: exec(/system/bin/getprop debug.mapview.logs @ maps.z.B.a:0)
[INFO]  I/Google Maps Android API: Google Play services client version: 7571000
[INFO]  I/Google Maps Android API: Google Play services package version: 9083246
[ERROR] MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
[INFO]  System: exec(/system/bin/getprop debug.mapview.gmmserver @ maps.z.B.a:0)
[INFO]  System: exec(/system/bin/getprop debug.mapview.renderer @ maps.z.B.a:0)
[INFO]  System: exec(/system/bin/getprop debug.mapview.pawprint @ maps.z.B.a:0)
[WARN]  ContextImpl: Failed to ensure directory: /storage/ext_sd/Android/data/com.emoney.app/cache
[INFO]  Choreographer: Skipped 96 frames!  The application may be doing too much work on its main thread.
[INFO]  b: Sending API token request.
[INFO]  b: Received API Token: AH0uPGFf38mllXZKTX4cF4dq-2srhsoArv4D1OyqpLYyNEh38sA5pdgtwRYySX8IlYDdm1nNlbVVNOXjUy7Ybq4DV87YpF8g44xL83e_051BXVnJZzXrwv1qe3-WVMoBvhVqOx9AE7kuX03le_kjoQ4VwiZ2f3BA1XP7ruNijLQVK-Ok2tcso-k / Expires in: 432000000ms
[INFO]  c: Scheduling next attempt in 431700 seconds.
[INFO]  d: Saved auth token
[INFO]  I/System.out: [CDS][DNS] getAllByNameImpl netId = 0
[INFO]  I/System.out: propertyValue:true
[INFO]  I/System.out: [CDS]rx timeout:2500
[INFO]  I/System.out: [socket][4] connection clients4.google.com/216.58.208.206:443;LocalPort=34558(2500)
[INFO]  I/System.out: [CDS]connect[clients4.google.com/216.58.208.206:443] tm:2
[INFO]  I/System.out: [socket][/192.168.1.2:34558] connected
[WARN]  HTCLOG: use specified tag [NativeCrypto], func [0].
[WARN]  HTCLOG: mask=0x18
[ERROR] NativeCrypto: ssl=0xabd25b40 cert_verify_callback x509_store_ctx=0xdc0c27b0 arg=0x0
[ERROR] NativeCrypto: ssl=0xabd25b40 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_ECDSA
[INFO]  I/System.out: gba_cipher_suite:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
[INFO]  I/System.out: [OkHttp] sendRequest<<
[ERROR] DynamiteModule: Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.android.gms.googlecertificates.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/com.meney.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.emoney.salla-2/lib/arm, /vendor/lib, /system/lib]]
[INFO]  DynamiteModule: Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:1
[INFO]  DynamiteModule: Selected remote version of com.google.android.gms.googlecertificates, version >= 1

```

**Comment by abada** [comment] 2016-05-31 10:48
Please see the map not shown correctly with error above 
![photo_2016-05-31_12-41-24](https://cloud.githubusercontent.com/assets/180586/15671959/ec2b5204-272d-11e6-8b15-2cab28494ec6.jpg)

**Comment by hansemannn** [comment] 2016-05-31 11:04
I cannot do anything with that screen...and I masked your API-key, since it was visible in your logs. Please provide the map-related code that reproduces your error and make sure you followed the readme to configure the module in your tiapp.xml. I am 90 % sure it's something on your side.

**Comment by hansemannn** [comment] 2016-05-31 11:07
UPDATE: It is something with your Google Play Services. It is currently a huge issue on the Google Maps side, related SO: http://stackoverflow.com/questions/37281942/google-map-api-v2-doesnt-work-since-google-play-services-update-9-0-83. Please follow the instructions there to fix it. Closing for now.

**Closed by hansemannn** 2016-05-31 11:07 UTC

**Comment by abada** [comment] 2016-05-31 11:13
That`s strange the map works fine in another window !
 
![photo_2016-05-31_13-04-16](https://cloud.githubusercontent.com/assets/180586/15672518/6558933c-2731-11e6-8e35-8b7869a3f076.jpg)

**Comment by abada** [comment] 2016-05-31 11:17
Please note i am using `Google Play Services` which attached with `ti.map` module !
