### ISSUE TITLE
Ti.map 2.5: Bad Memory Access - Crash

### ISSUE THREAD

**Issue by pebosi** [appcelerator-modules/ti.map#135] opened 2015-11-27 09:48 UTC
Updated my app to use ti.map 2.5, but when clicking on an annotation the app crashes with an Bad Memory Access [EXC_BAD_ACCESS // SIGSEGV // SIGBUS], error.
Switching back to 2.4.1 and the app works again

**Comment by designbymind** [comment] 2015-11-28 10:20
**+1** · I am also receiving the same error/crash whilst running 2.5.0. Really looking forward to the map styling of SATELLITE_FLYOVER_TYPE!

**Comment by yozef** [comment] 2015-11-28 12:50
Do you guys have polygons/circles overlays? If so this could very well be the issue. 
The Module loops through each of these overlays every time the map is tapped on (supposedly to return the overlay that got tapped on returned). I have removed these lines from the mapclick event in order not to do that. Not sure if this is the issue you guys face... but I think the community should be aware of it.

**Comment by designbymind** [comment] 2015-11-29 08:03
Hi @yozef,

Thanks for the response!

My app is crashing anytime there is an annotation added to the map using Ti.Map 2.5.0. I'm not using any overlays (polygon/circle). However, without any annotations/overlays, the map does render successfully. Looking forward to a fix because MapKit is looking better than ever & I can't wait to use the new 'Flyover' map types!

**Current environment:**
* Appcelerator Studio 4.4.0
* Ti SDK 5.1.1.GA
* iOS 9.1
* iPhone 5s / iPhone 6 / iPhone 6s (simulator)
* iPhone 6s / iPhone 6s Plus (device)

```php
 Jason 😃
```

**Comment by hansemannn** [comment] 2015-11-30 07:54
Hey guys! Can you provide a reproducible test case on this?

**Comment by designbymind** [comment] 2015-12-05 05:26
Hi @hansemannn,

I just wanted to note that I'm successfully able to get the new map type(s) to work.
However, when adding an overlay and/or annotation (annotation in my case), I'm experiencing an app crash when loading a window with a map view using Ti.Map 2.5.0.

**Sample code below:**

alloy.js
```javascript
Alloy.Globals.Map = require('ti.map');
```

map.xml
```xml
<Alloy>
    <Window id="mapWindow">
        <View id="map" module="ti.map" />
    </Window>
</Alloy>
```
map.js
```javascript
$.map.applyProperties({
	//mapType : Alloy.Globals.Map.NORMAL_TYPE,
	mapType : Alloy.Globals.Map.SATELLITE_FLYOVER_TYPE,
	region : {
		latitude : 33.653352,
		longitude : -117.750800,
		latitudeDelta : 0.03,
		longitudeDelta : 0.03
	},
	animate : true,
	regionFit : true,
	userLocation : true,
	showsPointsOfInterest : false,
	showsBuildings : true,
	pitchEnabled : true
});

var annotation = Alloy.Globals.Map.createAnnotation({
	latitude : 33.653352,
	longitude : -117.750800,
	title : "The Village",
	pincolor : Alloy.Globals.Map.ANNOTATION_RED,
	myid : 1
});

$.map.addAnnotation(annotation);
```

Please let me know if I can provide any additional info & thank you!

**Comment by hansemannn** [comment] 2015-12-05 11:45
Hi everyone! 

- This issue can be tracked here: https://jira.appcelerator.org/browse/MOD-2171
- The fix can be found here: https://github.com/hansemannn/titanium_mobile/blob/MOD-2171/support/module/packaged/ti.map-iphone-2.5.1.zip?raw=true

Let me know if the 2.5.1 works for everyone of you.

**Comment by designbymind** [comment] 2015-12-05 23:02
Hi @hansemannn,

Looks like since 2.5.1, both adding overlays & annotations works great now!

However, I have found that my app crashes when selecting annotations (by either clicking on map or by selecting programmatically)...

**Example:**
```javascript
$.map.selectAnnotation(annotation);
```

It seems as if this only occurs while the map is visible. I have tried two test cases:
One with the map hidden and then shown after completely loaded (with annotation added & selected). The other when a window opens, map is added, annotation is added to map, & annotation is selected. The latter appears to crash & fail on both simulator & device.

Any thoughts?

Just want to say thanks again for all the help on resolving this issue. You rock! 😎

**Comment by hansemannn** [comment] 2015-12-06 18:00
The crash on `selectAnnotation` did not happen before? Please provide a trace log here, thanks!

**Comment by hansemannn** [comment] 2015-12-08 21:07
Closing this issue for now, since no new crashes have been reported.

**Comment by pebosi** [comment] 2015-12-09 09:23
My issue was that the app crashes when "clicking on an annotation" (first comment). 
Tried version 2.5.1 with no luck.

**Comment by designbymind** [comment] 2015-12-09 09:30
**+1**

**Comment by hansemannn** [comment] 2015-12-09 15:29
@pebosi Then please provide an example code to reproduce your issue. I reopened the ticket for now.

**Comment by pebosi** [comment] 2015-12-10 08:56
Created an new simple alloy project with ti.map 2.5.1 in studio and generated some annotations.
- The app opens and shows the map with generated annotations (has worked before)
- when clicking on the first generated annotation the info window opens (as before)
- when clicking on any other annotation the app crashes (didn't crash on 2.4.1)

Tested only on iPad.

**Comment by hansemannn** [comment] 2015-12-10 08:58
We cannot do something without having an actual demo code like @designbymind and I provided. Please make sure to attach something in order to get it fixed. We also need a JIRA ticket before we can fix the ticket.

**Comment by pebosi** [comment] 2015-12-10 09:01
Code uploaded: https://gist.github.com/pebosi/bf93c55bc4878d64a4bf

**Comment by WillDent** [comment] 2015-12-10 20:01
Yep.. I can confirm this is happening on two of our apps now as well. :-(

**Comment by hansemannn** [comment] 2015-12-12 14:04
Hey Guys! First of all thanks @pebosi for the demo code! The issue was related to the index of the annotation that broke the code when being compiled with iOS 9.x. We fixed the issue and would like to test you the updated 2.5.2 version [here](https://www.dropbox.com/s/b4k5sceeivilcid/ti.map-iphone-2.5.2.zip?dl=0)

**Comment by designbymind** [comment] 2015-12-12 14:27
Thanks, @hansemannn!

All works great on my end. Tested on both simulator & device for two separate apps (iOS 9.2 only).

**Comment by WillDent** [comment] 2015-12-12 14:42
@hansemannn works great.  Thank you!

**Comment by pebosi** [comment] 2015-12-14 09:30
Yes, works for me too. Thx

**Comment by hansemannn** [comment] 2015-12-14 10:30
Closing then, thanks everyone!

**Closed by hansemannn** 2015-12-14 10:30 UTC
