### ISSUE TITLE
Zoom In on iOS maps give black screen with vertical and horizontal strips.

### ISSUE THREAD

**Issue by snehalhumne** [appcelerator-modules/ti.map#174] opened 2016-08-10 14:39 UTC
Hi, I have implemented the ti.map module in a project, there I have given the latitudeDelta and longitudeDelta value 0.005, Now when I pinch out on the screen it the map zoom but after specific zoom level, it shows the blank black screen with vertical and horizontal strips.
![img_0707](https://cloud.githubusercontent.com/assets/20770912/17557767/164752fa-5f36-11e6-8c15-3ab92a8a4a10.jpeg)

**Comment by hansemannn** [comment] 2016-08-10 16:57
Closing as duplicate of the JIRA-ticket. Please only create tickets on JIRA.

**Closed by hansemannn** 2016-08-10 16:57 UTC
